# coding: utf-8

"""
    Swagger b2c2

    B2C2 REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import b2c2_api
from b2c2_api.api.b2c2_api import B2c2Api  # noqa: E501
from b2c2_api.rest import ApiException


class TestB2c2Api(unittest.TestCase):
    """B2c2Api unit test stubs"""

    def setUp(self):
        self.api = b2c2_api.api.b2c2_api.B2c2Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_b2c2_balance_get(self):
        """Test case for b2c2_balance_get

        Get Balances  # noqa: E501
        """
        pass

    def test_b2c2_instruments_get(self):
        """Test case for b2c2_instruments_get

        Get Tradable Instruments  # noqa: E501
        """
        pass

    def test_b2c2_order_post(self):
        """Test case for b2c2_order_post

        Post an order  # noqa: E501
        """
        pass

    def test_b2c2_request_for_quote_post(self):
        """Test case for b2c2_request_for_quote_post

        API endpoint to send Request for Quotes.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
