# coding: utf-8

"""
    Swagger b2c2

    B2C2 REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import b2c2_api
from b2c2_api.models.trade import Trade  # noqa: E501
from b2c2_api.rest import ApiException

class TestTrade(unittest.TestCase):
    """Trade unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Trade
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = b2c2_api.models.trade.Trade()  # noqa: E501
        if include_optional :
            return Trade(
                instrument = '', 
                trade_id = '', 
                origin = '', 
                created = '', 
                price = '', 
                quantity = '', 
                order = '', 
                side = '', 
                executing_unit = ''
            )
        else :
            return Trade(
        )

    def testTrade(self):
        """Test Trade"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
