# coding: utf-8

"""
    Swagger b2c2

    B2C2 REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import b2c2_api
from b2c2_api.models.quote import Quote  # noqa: E501
from b2c2_api.rest import ApiException

class TestQuote(unittest.TestCase):
    """Quote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Quote
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = b2c2_api.models.quote.Quote()  # noqa: E501
        if include_optional :
            return Quote(
                valid_until = '', 
                rfq_id = '', 
                client_rfq_id = '', 
                quantity = '', 
                side = '', 
                instrument = '', 
                price = '', 
                created = ''
            )
        else :
            return Quote(
        )

    def testQuote(self):
        """Test Quote"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
