# coding: utf-8

# flake8: noqa
"""
    Swagger b2c2

    B2C2 REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from b2c2_api.models.instrument import Instrument
from b2c2_api.models.order import Order
from b2c2_api.models.order_request import OrderRequest
from b2c2_api.models.quote import Quote
from b2c2_api.models.quote_request import QuoteRequest
from b2c2_api.models.trade import Trade
