# coding: utf-8

"""
    Swagger b2c2

    B2C2 REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from b2c2_api.configuration import Configuration


class OrderRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'instrument': 'str',
        'side': 'str',
        'quantity': 'str',
        'client_order_id': 'str',
        'price': 'str',
        'order_type': 'str',
        'valid_until': 'str',
        'executing_unit': 'str'
    }

    attribute_map = {
        'instrument': 'instrument',
        'side': 'side',
        'quantity': 'quantity',
        'client_order_id': 'client_order_id',
        'price': 'price',
        'order_type': 'order_type',
        'valid_until': 'valid_until',
        'executing_unit': 'executing_unit'
    }

    def __init__(self, instrument=None, side=None, quantity=None, client_order_id=None, price=None, order_type=None, valid_until=None, executing_unit=None, local_vars_configuration=None):  # noqa: E501
        """OrderRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._instrument = None
        self._side = None
        self._quantity = None
        self._client_order_id = None
        self._price = None
        self._order_type = None
        self._valid_until = None
        self._executing_unit = None
        self.discriminator = None

        if instrument is not None:
            self.instrument = instrument
        if side is not None:
            self.side = side
        if quantity is not None:
            self.quantity = quantity
        if client_order_id is not None:
            self.client_order_id = client_order_id
        if price is not None:
            self.price = price
        if order_type is not None:
            self.order_type = order_type
        if valid_until is not None:
            self.valid_until = valid_until
        if executing_unit is not None:
            self.executing_unit = executing_unit

    @property
    def instrument(self):
        """Gets the instrument of this OrderRequest.  # noqa: E501


        :return: The instrument of this OrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._instrument

    @instrument.setter
    def instrument(self, instrument):
        """Sets the instrument of this OrderRequest.


        :param instrument: The instrument of this OrderRequest.  # noqa: E501
        :type instrument: str
        """

        self._instrument = instrument

    @property
    def side(self):
        """Gets the side of this OrderRequest.  # noqa: E501


        :return: The side of this OrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this OrderRequest.


        :param side: The side of this OrderRequest.  # noqa: E501
        :type side: str
        """

        self._side = side

    @property
    def quantity(self):
        """Gets the quantity of this OrderRequest.  # noqa: E501


        :return: The quantity of this OrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this OrderRequest.


        :param quantity: The quantity of this OrderRequest.  # noqa: E501
        :type quantity: str
        """

        self._quantity = quantity

    @property
    def client_order_id(self):
        """Gets the client_order_id of this OrderRequest.  # noqa: E501


        :return: The client_order_id of this OrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_order_id

    @client_order_id.setter
    def client_order_id(self, client_order_id):
        """Sets the client_order_id of this OrderRequest.


        :param client_order_id: The client_order_id of this OrderRequest.  # noqa: E501
        :type client_order_id: str
        """

        self._client_order_id = client_order_id

    @property
    def price(self):
        """Gets the price of this OrderRequest.  # noqa: E501


        :return: The price of this OrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this OrderRequest.


        :param price: The price of this OrderRequest.  # noqa: E501
        :type price: str
        """

        self._price = price

    @property
    def order_type(self):
        """Gets the order_type of this OrderRequest.  # noqa: E501


        :return: The order_type of this OrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._order_type

    @order_type.setter
    def order_type(self, order_type):
        """Sets the order_type of this OrderRequest.


        :param order_type: The order_type of this OrderRequest.  # noqa: E501
        :type order_type: str
        """

        self._order_type = order_type

    @property
    def valid_until(self):
        """Gets the valid_until of this OrderRequest.  # noqa: E501


        :return: The valid_until of this OrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._valid_until

    @valid_until.setter
    def valid_until(self, valid_until):
        """Sets the valid_until of this OrderRequest.


        :param valid_until: The valid_until of this OrderRequest.  # noqa: E501
        :type valid_until: str
        """

        self._valid_until = valid_until

    @property
    def executing_unit(self):
        """Gets the executing_unit of this OrderRequest.  # noqa: E501


        :return: The executing_unit of this OrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._executing_unit

    @executing_unit.setter
    def executing_unit(self, executing_unit):
        """Sets the executing_unit of this OrderRequest.


        :param executing_unit: The executing_unit of this OrderRequest.  # noqa: E501
        :type executing_unit: str
        """

        self._executing_unit = executing_unit

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrderRequest):
            return True

        return self.to_dict() != other.to_dict()
