# coding: utf-8

"""
    Swagger b2c2

    B2C2 REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from b2c2_api.configuration import Configuration


class Order(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'order_id': 'str',
        'client_order_id': 'str',
        'quantity': 'str',
        'side': 'str',
        'instrument': 'str',
        'price': 'str',
        'executed_price': 'str',
        'executing_unit': 'str',
        'created': 'str',
        'trades': 'list[Trade]'
    }

    attribute_map = {
        'order_id': 'order_id',
        'client_order_id': 'client_order_id',
        'quantity': 'quantity',
        'side': 'side',
        'instrument': 'instrument',
        'price': 'price',
        'executed_price': 'executed_price',
        'executing_unit': 'executing_unit',
        'created': 'created',
        'trades': 'trades'
    }

    def __init__(self, order_id=None, client_order_id=None, quantity=None, side=None, instrument=None, price=None, executed_price=None, executing_unit=None, created=None, trades=None, local_vars_configuration=None):  # noqa: E501
        """Order - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._order_id = None
        self._client_order_id = None
        self._quantity = None
        self._side = None
        self._instrument = None
        self._price = None
        self._executed_price = None
        self._executing_unit = None
        self._created = None
        self._trades = None
        self.discriminator = None

        if order_id is not None:
            self.order_id = order_id
        if client_order_id is not None:
            self.client_order_id = client_order_id
        if quantity is not None:
            self.quantity = quantity
        if side is not None:
            self.side = side
        if instrument is not None:
            self.instrument = instrument
        if price is not None:
            self.price = price
        if executed_price is not None:
            self.executed_price = executed_price
        if executing_unit is not None:
            self.executing_unit = executing_unit
        if created is not None:
            self.created = created
        if trades is not None:
            self.trades = trades

    @property
    def order_id(self):
        """Gets the order_id of this Order.  # noqa: E501


        :return: The order_id of this Order.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this Order.


        :param order_id: The order_id of this Order.  # noqa: E501
        :type order_id: str
        """

        self._order_id = order_id

    @property
    def client_order_id(self):
        """Gets the client_order_id of this Order.  # noqa: E501


        :return: The client_order_id of this Order.  # noqa: E501
        :rtype: str
        """
        return self._client_order_id

    @client_order_id.setter
    def client_order_id(self, client_order_id):
        """Sets the client_order_id of this Order.


        :param client_order_id: The client_order_id of this Order.  # noqa: E501
        :type client_order_id: str
        """

        self._client_order_id = client_order_id

    @property
    def quantity(self):
        """Gets the quantity of this Order.  # noqa: E501


        :return: The quantity of this Order.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this Order.


        :param quantity: The quantity of this Order.  # noqa: E501
        :type quantity: str
        """

        self._quantity = quantity

    @property
    def side(self):
        """Gets the side of this Order.  # noqa: E501


        :return: The side of this Order.  # noqa: E501
        :rtype: str
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this Order.


        :param side: The side of this Order.  # noqa: E501
        :type side: str
        """

        self._side = side

    @property
    def instrument(self):
        """Gets the instrument of this Order.  # noqa: E501


        :return: The instrument of this Order.  # noqa: E501
        :rtype: str
        """
        return self._instrument

    @instrument.setter
    def instrument(self, instrument):
        """Sets the instrument of this Order.


        :param instrument: The instrument of this Order.  # noqa: E501
        :type instrument: str
        """

        self._instrument = instrument

    @property
    def price(self):
        """Gets the price of this Order.  # noqa: E501


        :return: The price of this Order.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this Order.


        :param price: The price of this Order.  # noqa: E501
        :type price: str
        """

        self._price = price

    @property
    def executed_price(self):
        """Gets the executed_price of this Order.  # noqa: E501


        :return: The executed_price of this Order.  # noqa: E501
        :rtype: str
        """
        return self._executed_price

    @executed_price.setter
    def executed_price(self, executed_price):
        """Sets the executed_price of this Order.


        :param executed_price: The executed_price of this Order.  # noqa: E501
        :type executed_price: str
        """

        self._executed_price = executed_price

    @property
    def executing_unit(self):
        """Gets the executing_unit of this Order.  # noqa: E501


        :return: The executing_unit of this Order.  # noqa: E501
        :rtype: str
        """
        return self._executing_unit

    @executing_unit.setter
    def executing_unit(self, executing_unit):
        """Sets the executing_unit of this Order.


        :param executing_unit: The executing_unit of this Order.  # noqa: E501
        :type executing_unit: str
        """

        self._executing_unit = executing_unit

    @property
    def created(self):
        """Gets the created of this Order.  # noqa: E501


        :return: The created of this Order.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Order.


        :param created: The created of this Order.  # noqa: E501
        :type created: str
        """

        self._created = created

    @property
    def trades(self):
        """Gets the trades of this Order.  # noqa: E501


        :return: The trades of this Order.  # noqa: E501
        :rtype: list[Trade]
        """
        return self._trades

    @trades.setter
    def trades(self, trades):
        """Sets the trades of this Order.


        :param trades: The trades of this Order.  # noqa: E501
        :type trades: list[Trade]
        """

        self._trades = trades

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Order):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Order):
            return True

        return self.to_dict() != other.to_dict()
