# coding: utf-8

"""
    Swagger b2c2

    B2C2 REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from b2c2_api.configuration import Configuration


class QuoteRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'instrument': 'str',
        'side': 'str',
        'quantity': 'str',
        'client_rfq_id': 'str'
    }

    attribute_map = {
        'instrument': 'instrument',
        'side': 'side',
        'quantity': 'quantity',
        'client_rfq_id': 'client_rfq_id'
    }

    def __init__(self, instrument=None, side=None, quantity=None, client_rfq_id=None, local_vars_configuration=None):  # noqa: E501
        """QuoteRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._instrument = None
        self._side = None
        self._quantity = None
        self._client_rfq_id = None
        self.discriminator = None

        if instrument is not None:
            self.instrument = instrument
        if side is not None:
            self.side = side
        if quantity is not None:
            self.quantity = quantity
        if client_rfq_id is not None:
            self.client_rfq_id = client_rfq_id

    @property
    def instrument(self):
        """Gets the instrument of this QuoteRequest.  # noqa: E501


        :return: The instrument of this QuoteRequest.  # noqa: E501
        :rtype: str
        """
        return self._instrument

    @instrument.setter
    def instrument(self, instrument):
        """Sets the instrument of this QuoteRequest.


        :param instrument: The instrument of this QuoteRequest.  # noqa: E501
        :type instrument: str
        """

        self._instrument = instrument

    @property
    def side(self):
        """Gets the side of this QuoteRequest.  # noqa: E501


        :return: The side of this QuoteRequest.  # noqa: E501
        :rtype: str
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this QuoteRequest.


        :param side: The side of this QuoteRequest.  # noqa: E501
        :type side: str
        """

        self._side = side

    @property
    def quantity(self):
        """Gets the quantity of this QuoteRequest.  # noqa: E501


        :return: The quantity of this QuoteRequest.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this QuoteRequest.


        :param quantity: The quantity of this QuoteRequest.  # noqa: E501
        :type quantity: str
        """

        self._quantity = quantity

    @property
    def client_rfq_id(self):
        """Gets the client_rfq_id of this QuoteRequest.  # noqa: E501


        :return: The client_rfq_id of this QuoteRequest.  # noqa: E501
        :rtype: str
        """
        return self._client_rfq_id

    @client_rfq_id.setter
    def client_rfq_id(self, client_rfq_id):
        """Sets the client_rfq_id of this QuoteRequest.


        :param client_rfq_id: The client_rfq_id of this QuoteRequest.  # noqa: E501
        :type client_rfq_id: str
        """

        self._client_rfq_id = client_rfq_id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuoteRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, QuoteRequest):
            return True

        return self.to_dict() != other.to_dict()
