# coding: utf-8

"""
    Swagger b2c2

    B2C2 REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from b2c2_api.configuration import Configuration


class Quote(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'valid_until': 'str',
        'rfq_id': 'str',
        'client_rfq_id': 'str',
        'quantity': 'str',
        'side': 'str',
        'instrument': 'str',
        'price': 'str',
        'created': 'str'
    }

    attribute_map = {
        'valid_until': 'valid_until',
        'rfq_id': 'rfq_id',
        'client_rfq_id': 'client_rfq_id',
        'quantity': 'quantity',
        'side': 'side',
        'instrument': 'instrument',
        'price': 'price',
        'created': 'created'
    }

    def __init__(self, valid_until=None, rfq_id=None, client_rfq_id=None, quantity=None, side=None, instrument=None, price=None, created=None, local_vars_configuration=None):  # noqa: E501
        """Quote - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._valid_until = None
        self._rfq_id = None
        self._client_rfq_id = None
        self._quantity = None
        self._side = None
        self._instrument = None
        self._price = None
        self._created = None
        self.discriminator = None

        if valid_until is not None:
            self.valid_until = valid_until
        if rfq_id is not None:
            self.rfq_id = rfq_id
        if client_rfq_id is not None:
            self.client_rfq_id = client_rfq_id
        if quantity is not None:
            self.quantity = quantity
        if side is not None:
            self.side = side
        if instrument is not None:
            self.instrument = instrument
        if price is not None:
            self.price = price
        if created is not None:
            self.created = created

    @property
    def valid_until(self):
        """Gets the valid_until of this Quote.  # noqa: E501


        :return: The valid_until of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._valid_until

    @valid_until.setter
    def valid_until(self, valid_until):
        """Sets the valid_until of this Quote.


        :param valid_until: The valid_until of this Quote.  # noqa: E501
        :type valid_until: str
        """

        self._valid_until = valid_until

    @property
    def rfq_id(self):
        """Gets the rfq_id of this Quote.  # noqa: E501


        :return: The rfq_id of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._rfq_id

    @rfq_id.setter
    def rfq_id(self, rfq_id):
        """Sets the rfq_id of this Quote.


        :param rfq_id: The rfq_id of this Quote.  # noqa: E501
        :type rfq_id: str
        """

        self._rfq_id = rfq_id

    @property
    def client_rfq_id(self):
        """Gets the client_rfq_id of this Quote.  # noqa: E501


        :return: The client_rfq_id of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._client_rfq_id

    @client_rfq_id.setter
    def client_rfq_id(self, client_rfq_id):
        """Sets the client_rfq_id of this Quote.


        :param client_rfq_id: The client_rfq_id of this Quote.  # noqa: E501
        :type client_rfq_id: str
        """

        self._client_rfq_id = client_rfq_id

    @property
    def quantity(self):
        """Gets the quantity of this Quote.  # noqa: E501


        :return: The quantity of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this Quote.


        :param quantity: The quantity of this Quote.  # noqa: E501
        :type quantity: str
        """

        self._quantity = quantity

    @property
    def side(self):
        """Gets the side of this Quote.  # noqa: E501


        :return: The side of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this Quote.


        :param side: The side of this Quote.  # noqa: E501
        :type side: str
        """

        self._side = side

    @property
    def instrument(self):
        """Gets the instrument of this Quote.  # noqa: E501


        :return: The instrument of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._instrument

    @instrument.setter
    def instrument(self, instrument):
        """Sets the instrument of this Quote.


        :param instrument: The instrument of this Quote.  # noqa: E501
        :type instrument: str
        """

        self._instrument = instrument

    @property
    def price(self):
        """Gets the price of this Quote.  # noqa: E501


        :return: The price of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this Quote.


        :param price: The price of this Quote.  # noqa: E501
        :type price: str
        """

        self._price = price

    @property
    def created(self):
        """Gets the created of this Quote.  # noqa: E501


        :return: The created of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Quote.


        :param created: The created of this Quote.  # noqa: E501
        :type created: str
        """

        self._created = created

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Quote):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Quote):
            return True

        return self.to_dict() != other.to_dict()
