# coding: utf-8

# flake8: noqa

"""
    Swagger b2c2

    B2C2 REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from b2c2_api.api.b2c2_api import B2c2Api

# import ApiClient
from b2c2_api.api_client import ApiClient
from b2c2_api.configuration import Configuration
from b2c2_api.exceptions import OpenApiException
from b2c2_api.exceptions import ApiTypeError
from b2c2_api.exceptions import ApiValueError
from b2c2_api.exceptions import ApiKeyError
from b2c2_api.exceptions import ApiAttributeError
from b2c2_api.exceptions import ApiException
# import models into sdk package
from b2c2_api.models.instrument import Instrument
from b2c2_api.models.order import Order
from b2c2_api.models.order_request import OrderRequest
from b2c2_api.models.quote import Quote
from b2c2_api.models.quote_request import QuoteRequest
from b2c2_api.models.trade import Trade

